export interface SkillHubTrustedRootKey {
  keyId: string;
  algorithm: 'ed25519';
  publicKeyPem: string;
}

/**
 * CatsCo SkillHub trust anchors.
 *
 * Generated by scripts/update-skillhub-root-key.mjs. The matching root private
 * key must stay on the SkillHub cloud side and must not be bundled in Agent.
 */
export const CATSCO_SKILLHUB_ROOT_PUBLIC_KEYS: SkillHubTrustedRootKey[] = [
  {
    keyId: "catsco-root-prod-2026-01",
    algorithm: 'ed25519',
    publicKeyPem: `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAJIkLx7f1l5/FZe54/gI7t/BJdMS3SqO7wBIAHQzZZSw=
-----END PUBLIC KEY-----`,
  },
];
