export type ContentBlock =
  | { type: 'text'; text: string }
  | { type: 'image'; source: { type: 'base64'; media_type: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp'; data: string } };

export type ProviderContentBlock = Record<string, unknown> & { type: string };
export type ProviderApiType = 'anthropic-messages' | 'openai-chat-completions' | 'openai-responses';

/** Opaque scope that prevents provider-only replay state crossing model/API boundaries. */
export interface ProviderStateReference {
  schema: 'xiaoba.provider_state.v1';
  apiType: ProviderApiType;
  model: string;
  endpointFingerprint: string;
}
export type ReasoningEffort = 'default' | 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max' | 'disabled';
export type OpenAIApiMode = 'chat_completions' | 'responses';

export interface Message {
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string | ContentBlock[] | null;
  tool_calls?: Array<{
    id: string;
    type: 'function';
    function: {
      name: string;
      arguments: string;
    };
  }>;
  tool_call_id?: string;
  name?: string;
  /** 标记由 injectContext 注入的消息，用于滑动窗口清理 */
  __injected?: boolean;
  /**
   * Provider-only cache placement hint. Dynamic system context remains system-priority
   * but is appended to Responses input instead of destabilizing instructions.
   */
  __cacheScope?: 'stable' | 'dynamic';
  /** 标记注入给 agent 看的运行时反馈，仅供内部清理和日志记录使用 */
  __runtimeFeedback?: boolean;
  /** 标记内部 runtime observation，例如子 agent 完成结果；对模型仍以 user role 承载 */
  __runtimeObservation?: boolean;
  runtimeObservationSource?: string;
  /** 标记内部错误占位，仅用于本地恢复/继续，不应进入模型上下文或持久历史。 */
  __internalErrorArtifact?: boolean;
  /** Synthetic tool-call/tool-result pair used as transient runtime context. */
  __syntheticObservation?: boolean;
  syntheticObservationId?: string;
  /** Internal episode marker used for local compaction grouping. Never sent to providers. */
  __episodeId?: string;
  /** Distinguishes the initial user input from user messages merged while a turn is running. */
  __episodeInputKind?: 'root' | 'pending';
  /** Durable continuation checkpoint generated by the main Agent compaction chain. */
  __checkpointSummary?: boolean;
  /** Durable marker for a continuation checkpoint boundary. */
  __checkpointBoundary?: boolean;
  /** Internal compaction phase. Never sent to providers. */
  __checkpointPhase?: 'pre_turn' | 'mid_turn' | 'restore';
  /** 远端耐久上下文来源和消息序号，用于游标写盘失败后的幂等补拉。 */
  __remoteContextSource?: string;
  __remoteContextId?: number;
  /** 压缩后仍被当前 transcript 表示的远端消息高水位；不发送给 provider。 */
  __remoteContextWatermarks?: Record<string, number>;
  /** Provider 原始 assistant content blocks，仅用于下次请求回放，不展示给用户。 */
  providerContent?: ProviderContentBlock[];
  /** Identity of the provider boundary that produced providerContent. Never sent verbatim. */
  providerState?: ProviderStateReference;
}

export interface ChatConfig {
  apiKey?: string;
  apiUrl?: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
  contextWindowTokens?: number;
  reasoningEffort?: ReasoningEffort;
  openaiApiMode?: OpenAIApiMode;
  /** Capability facts supplied by the selected model catalog, when available. */
  modelCapabilities?: {
    vision?: boolean;
    toolCalling?: boolean;
    streaming?: boolean;
  };
  /** Optional OpenAI-compatible multimodal provider used when the primary model cannot receive images. */
  visionFallback?: {
    enabled?: boolean;
    usePrimaryModel?: boolean;
    baseUrl?: string;
    apiKey?: string;
    model?: string;
    timeoutMs?: number;
    maxTokens?: number;
  };
  provider?: 'openai' | 'anthropic';
  feishu?: {
    appId?: string;
    appSecret?: string;
    sessionTTL?: number;
    botOpenId?: string;
    botAliases?: string[];
  };
  catscompany?: {
    serverUrl?: string;
    apiKey?: string;
    httpBaseUrl?: string;
    sessionTTL?: number;
  };
  weixin?: {
    token?: string;
    baseUrl?: string;
    cdnBaseUrl?: string;
    allowFrom?: string[];
    sessionTTL?: number;
    longPollTimeout?: number;
  };
  catscoLogUpload?: {
    enabled?: boolean;
    serverUrl?: string;
    intervalMinutes?: number;
  };
}

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  cachedReadTokens?: number;
  cachedWriteTokens?: number;
}

export interface ChatResponse {
  content: string | null;
  toolCalls?: Array<{
    id: string;
    type: 'function';
    function: {
      name: string;
      arguments: string;
    };
  }>;
  usage?: TokenUsage;
  /** Provider stop/finish reason, e.g. max_tokens/length/tool_use/stop. */
  stopReason?: string;
  /** Provider 原始 assistant content blocks，仅用于下次请求回放，不展示给用户。 */
  providerContent?: ProviderContentBlock[];
  /** Identity of the provider boundary that produced providerContent. Never sent verbatim. */
  providerState?: ProviderStateReference;
}

export interface CommandOptions {
  interactive?: boolean;
  message?: string;
  config?: string;
  skill?: string;
}

// 导出 Agent 相关类型
export * from './agent';
export * from './tool';
export * from './skill';
export * from './session-identity';
