export const agentRunBoardHtml = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Agent Run Board</title><style>
:root{color-scheme:dark;--bg:#0b0f14;--panel:#121820;--line:#26303c;--muted:#8996a6;--text:#eef3f8;--active:#65d6ad;--blocked:#ff8e72;--done:#7ba7ff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button{font:inherit}.shell{max-width:1440px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.eyebrow,.label{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.12em}.top h1{font:600 28px/1.1 system-ui;margin:5px 0}.stamp{color:var(--muted)}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px}.metric,.list,.detail{border:1px solid var(--line);background:var(--panel);border-radius:10px}.metric{padding:14px 16px}.metric b{display:block;font:600 26px system-ui;margin-top:3px}.workspace{display:grid;grid-template-columns:minmax(300px,38%) 1fr;gap:14px}.panehead{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;border-bottom:1px solid var(--line)}#refresh{border:1px solid var(--line);border-radius:6px;background:transparent;color:var(--text);padding:6px 10px;cursor:pointer}.runs{max-height:calc(100vh - 235px);overflow:auto}.run{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid var(--line);background:transparent;color:inherit;padding:13px 14px;cursor:pointer}.run:hover,.run.selected{background:#19212b}.runline{display:flex;justify-content:space-between;gap:12px}.goal{margin-top:6px;color:#c8d1dc;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status{font-size:11px;text-transform:uppercase}.active,.queued,.waiting_for_input{color:var(--active)}.blocked{color:var(--blocked)}.completed,.cancelled{color:var(--done)}.detail{padding:18px;min-height:460px}.detail h2{font:600 22px system-ui;margin:5px 0 18px;overflow-wrap:anywhere}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.field{border-top:1px solid var(--line);padding-top:9px;min-width:0}.value{margin-top:5px;white-space:pre-wrap;overflow-wrap:anywhere}.wide{grid-column:1/-1}.timeline{list-style:none;padding:0;margin:8px 0}.timeline li{border-left:1px solid var(--line);padding:0 0 15px 15px;margin-left:5px}.timeline time{display:block;color:var(--muted);font-size:11px}.empty{color:var(--muted);padding:28px}.error{color:var(--blocked)}
@media(max-width:760px){.shell{padding:16px}.top{align-items:start}.stamp{display:none}.summary{gap:7px}.metric{padding:10px}.metric b{font-size:22px}.workspace{grid-template-columns:1fr}.runs{max-height:320px}.detail{min-height:0}.grid{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head><body><main class="shell"><header class="top"><div><div class="eyebrow">Read-only projection</div><h1>Agent Run Board</h1></div><div class="stamp" id="stamp">Loading…</div></header><section class="summary"><div class="metric"><span class="label">Running</span><b id="running">—</b></div><div class="metric"><span class="label">Blocked</span><b id="blocked">—</b></div><div class="metric"><span class="label">Complete</span><b id="complete">—</b></div></section><section class="workspace"><div class="list"><div class="panehead"><span class="label">Runs</span><button id="refresh">Refresh</button></div><div class="runs" id="runs"></div></div><article class="detail" id="detail"><div class="empty">Select a run.</div></article></section></main><script>
const $=id=>document.getElementById(id);let runs=[],selected='';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dt=v=>v?new Date(v).toLocaleString():'Not available';
function bucket(s){return ['completed','cancelled'].includes(s)?'complete':s==='blocked'?'blocked':'running'}
function renderList(){const counts={running:0,blocked:0,complete:0};runs.forEach(r=>counts[bucket(r.status)]++);Object.keys(counts).forEach(k=>$(k).textContent=counts[k]);$('runs').innerHTML=runs.length?runs.map(r=>'<button class="run '+(r.runId===selected?'selected':'')+'" data-id="'+esc(r.runId)+'"><span class="runline"><strong>'+esc(r.runType)+'</strong><span class="status '+esc(r.status)+'">'+esc(r.status.replaceAll('_',' '))+'</span></span><div class="goal">'+esc(r.initialGoal)+'</div></button>').join(''):'<div class="empty">No runs yet.</div>';$('runs').querySelectorAll('.run').forEach(b=>b.onclick=()=>select(b.dataset.id))}
function field(label,value,wide=false){return '<div class="field '+(wide?'wide':'')+'"><div class="label">'+label+'</div><div class="value">'+value+'</div></div>'}
function eventMatch(r,re){return [...r.events].reverse().find(e=>re.test(e.type+' '+e.summary))}
function renderDetail(r){const final=eventMatch(r,/final|complete|result|finish/i);const next=eventMatch(r,/next.action|next step|resume|wake/i);const block=eventMatch(r,/block|wait|input/i);const timeline=[...r.events].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('detail').innerHTML='<div class="eyebrow">'+esc(r.status.replaceAll('_',' '))+'</div><h2>'+esc(r.initialGoal)+'</h2><div class="grid">'+field('Trigger',esc(r.trigger.source+' · '+r.trigger.id+(r.trigger.summary?' · '+r.trigger.summary:'')),true)+field('Session','Protected by public projection')+field('Iteration / events',String(r.events.length))+field('Last final',final?esc(final.summary):'Not published')+field('Goal check',r.lastGoalCheck?esc((r.lastGoalCheck.complete?'Complete':'Incomplete')+' · checked '+dt(r.lastGoalCheck.checkedAt)):'Not published')+field('Next action',next?esc(next.summary):(r.lastGoalCheck?.hasNextAction?'Present but protected':'None published'))+field('Blocker',block?esc(block.summary):(r.blocked?'Present but protected':'None'))+field('Artifacts',r.artifacts.length?r.artifacts.map(a=>esc(a.label+' · '+a.kind)).join('<br>'):'None published',true)+field('Timeline',timeline.length?'<ol class="timeline">'+timeline.map(e=>'<li><time>'+esc(dt(e.createdAt))+'</time><strong>'+esc(e.type)+'</strong><br>'+esc(e.summary)+'</li>').join('')+'</ol>':'No public events',true)+'</div>'}
async function select(id){selected=id;renderList();const res=await fetch('/api/runs/'+encodeURIComponent(id));if(!res.ok){$('detail').innerHTML='<div class="empty error">Run unavailable.</div>';return}renderDetail(await res.json())}
async function load(){try{const res=await fetch('/api/runs');if(!res.ok)throw new Error('HTTP '+res.status);runs=await res.json();$('stamp').textContent='Updated '+new Date().toLocaleTimeString();renderList();if(selected&&runs.some(r=>r.runId===selected))await select(selected);else if(runs[0])await select(runs[0].runId);else $('detail').innerHTML='<div class="empty">No run selected.</div>'}catch(e){$('runs').innerHTML='<div class="empty error">Projection unavailable.</div>';$('stamp').textContent='Refresh failed'}}$('refresh').onclick=load;load();
</script></body></html>`;
